### ISSUE TITLE
Errors and missing textures in pre-release

### ISSUE THREAD

**Issue by Talyrius** [Muehe/classicdb#1]
Using the pre-release version you [asked me to try](https://github.com/AeroScripts/QuestieDev/issues/402) results in many errors and missing or broken textures. I couldn't get any quest notes to display on the map at all. I also tried running the two addons from the pre-release exclusively and it made no difference.

![image](https://cloud.githubusercontent.com/assets/1068810/23331030/38eea484-fb12-11e6-9a16-18f2676f6f13.png)

**Comment by Muehe** [comment]
Got it to reproduce now. Will let you know once I fixed it.

**Comment by Muehe** [comment]
Ok, think I got it:

[classicdb1.0-prerelease2.zip](https://github.com/Muehe/classicdb/files/801389/classicdb1.0-prerelease2.zip)

P.S.: Forgot to update the image paths and still had ShaguDB on my dev machine, so it was loading them from there.

**Comment by Talyrius** [comment]
The map notes for the quest objectives are still showing the question mark icon:
![image](https://cloud.githubusercontent.com/assets/1068810/23338570/660c2340-fbc3-11e6-8eb1-0ab28ef0eb99.png)

![image](https://cloud.githubusercontent.com/assets/1068810/23338540/6759688a-fbc2-11e6-957a-904b7f18fe45.png)

**Comment by Muehe** [comment]
Your chat message seems to indicate some icons might have names conflicting with another addon. I will rename them, which should solve this problem in theory. Also a list of your addons would be helpful, so I can do some testing as to which one is causing this. Furthermore, which quest where you trying to display, and how?

**Comment by Talyrius** [comment]
The quest objective notes displayed in my previous screenshot were for [The Strength of Corruption](http://db.vanillagaming.org/?quest=4120). The first screenshot shows the ClassicDB settings used.

A list of the addons I currently use:
```batchfile
dir /b /a:d /o:n | findstr /v "Blizzard_" > addons.txt
```
```text
!ImprovedErrorFrame
!Questie
!toggle
_LazyPig
Atlas
AtlasLoot
AutoBuff
aux-addon
Cartographer
Cartographer_ExtraIcons
Cartographer_Herbalism
Cartographer_Mining
ClassicDB
Clean_Up
DPSMate
EnhTooltip
EQL3
FlightMap
GFW_FeedOMatic
GFW_HuntersHelper
HealComm
Informant
KLHThreatMeter
linkmend
MCP
MikScrollingBattleText
MikScrollingBattleTextOptions
MobHealth
MobHealth3_BlizzardFrames
NiceDamage
pfUI
Postal
QuickHeal
ShaguInventory
ShaguKill
ShaguStance
SnaFu
Stubby
SuperMacro
WIM
```

**Comment by Muehe** [comment]
Thanks for the information, will try to reproduce this later. I finished the icon renaming, hope it helps:

[classicdb1.0-prerelease3.zip](https://github.com/Muehe/classicdb/files/802481/classicdb1.0-prerelease3.zip)

By the way, are you using a pre-installed version of Cartographer, or the one provided in the download?

**Comment by Talyrius** [comment]
> By the way, are you using a pre-installed version of Cartographer, or the one provided in the download?

The one that has been provided, of course. :stuck_out_tongue_winking_eye:

**Comment by Muehe** [comment]
Got it to reproduce, the `Cartographer_ExtraIcons` addon was causing this issue, since it had a conflicting icon name. Tested with prerelease3 as well and the issue should be fixed.

**Comment by Muehe** [comment]
By the way, I was planning on adding different icon settings at some point in the future. I might add a `Cartographer_ExtraIcons` profile if Shaun Dreclin gives his permission.
